# List breweries
query Breweries($cursor: String) {
    breweries(first: 25, after: $cursor) @connection(key: "default_breweries") {
        totalCount
        pageInfo {
            startCursor
            hasNextPage
            hasPreviousPage
            endCursor
        }
        edges {
            cursor
            node {
                id
                ...BreweryBaseFields
            }
        }
    }
}

query NearbyBreweries(
    $cursor: String
    $latitude: Decimal!
    $longitude: Decimal!
) {
    breweries: nearbyBreweries(
        first: 25
        after: $cursor
        latitude: $latitude
        longitude: $longitude
    ) {
        totalCount
        pageInfo {
            startCursor
            hasNextPage
            hasPreviousPage
            endCursor
        }
        edges {
            cursor
            node {
                id
                ...BreweryBaseFields
                latitude
                longitude
            }
        }
    }
}

query Autocomplete($search: String) {
    breweries(first: 10, search: $search) {
        totalCount
        edges {
            cursor
            node {
                name
                id
                brewery_id
                city
                state
            }
        }
    }
}

# Get Brewery by the id
query Brewery($id: ID!) {
    brewery: node(id: $id) {
        id
        ...BreweryDetailFields
    }
}

# Get Brewery by the brewery_id
query BreweryById($brewery_id: String!) {
    brewery: breweryById(brewery_id: $brewery_id) {
        id
        ...BreweryDetailFields
    }
}

fragment BreweryBaseFields on Brewery {
    name
    brewery_id
    street
    city
    state
    country
    website_url
    brewery_type
}

fragment BreweryDetailFields on Brewery {
    name
    brewery_id
    street
    city
    state
    country
    website_url
    brewery_type
    tag_list
    phone
    latitude
    longitude
    nearby(within: 15) {
        id
        ...BreweryBaseFields
        latitude
        longitude
    }
}
